#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

#Metrics related configurations
management.endpoint.metrics.enabled: "true"
management.endpoints.web.exposure.include: "*"
management.endpoint.prometheus.enabled: "true"
management.metrics.export.prometheus.enabled: "true"
management.metrics.web.server.auto-time-requests: "true"

#opentracing.jaeger.enabled: "true"

# Remove H2 from compile scope
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

endpoints.health.sensitive: "false"
info.app.name: '@name@'
info.app.description: Microservice chassis app
info.app.version: '@version@'
info.app.legal: "COPYRIGHT Ericsson 2021 -
 The copyright to the computer program(s) herein is the property of
 Ericsson Inc. The programs may be used and/or copied only with written
 permission from Ericsson Inc. or in accordance with the terms and
 conditions stipulated in the agreement/contract under which the
 program(s) have been supplied."

#See more details about pattern layout: https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/PatternLayout.html
#See more details about logging.pattern.level : https://docs.spring.io/spring-boot/docs/2.5.2/reference/html/features.html#features.logging.custom-log-configuration
#logging.pattern.level: "%5p [%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}][%X{userName}]"

#Set the stubrunner credentials:
#stubrunner.username: <LAN SIGNUM ID>
#stubrunner.password: <LAN encripted PWD or JFrog API Key>
stubrunner.username: ${SELI_ARTIFACTORY_REPO_USER}
stubrunner.password: ${SELI_ARTIFACTORY_REPO_PASS}


gateway.scheme: ${GATEWAY_SCHEME:http}
gateway.host: ${GATEWAY_HOST:localhost}
gateway.port: ${GATEWAY_PORT:8081}
gateway.insecure: ${GATEWAY_INSECURE:false}
gateway.auth.login: ${GATEWAY_AUTH_LOGIN:cts-user}
gateway.auth.password: ${GATEWAY_AUTH_PASSWORD:Ericsson123!}
gateway.auth.tenant: ${GATEWAY_AUTH_TENANT:master}
gateway.auth.session: ${GATEWAY_AUTH_SESSION:}
gateway.auth.refresh-period: ${GATEWAY_AUTH_REFRESH_PERIOD:3600}
gateway.retry.maxAttempts: ${RETRY_MAX_ATTEMPTS:3}
gateway.retry.maxDelay: ${RETRY_MAX_DELAY:1000}
gateway.retry.maxDelayEnmOverload: ${RETRY_MAX_DELAY_OVERLOAD:50000}
gateway.services.cts.url: ${CTS_URL:}
gateway.services.cts.base-path: ${CTS_BASE_PATH:}
gateway.services.cts.headers: ${CTS_HEADERS:}
gateway.services.ncmp.url: ${NCMP_URL:}
gateway.services.ncmp.base-path: ${NCMP_BASE_PATH:}
gateway.services.ncmp.headers: ${NCMP_HEADERS:}