#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- $serviceMesh := include "eric-oss-cell-sleep.service-mesh-enabled" . | trim -}}
{{- if eq $serviceMesh "true" }}

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ template "eric-oss-cell-sleep.fullname" . }}-virtualservice
  labels:
    {{- include "eric-oss-cell-sleep.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-oss-cell-sleep.prometheus" . | nindent 4 }}
    {{- include "eric-oss-cell-sleep.annotations" . | nindent 4 }}
spec:
  hosts:
  - {{ template "eric-oss-cell-sleep.fullname" . }}
  http:
    - name: {{ template "eric-oss-cell-sleep.fullname" . }}-http
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ template "eric-oss-cell-sleep.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}